# Enable global discounts
enable-global-discounts: true
# Enable guaranteed zombification
enable-guaranteed-zombification: true
# Enable easy zombie containment
enable-easy-zombie-containment: true
# Enable sending stats to bStats
enable-bstats: true
# Enable plugin
enable-plugin: true